/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PresentationLayer;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JSpinner.DefaultEditor;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author hasaan
 */
public class CreatePuzzleJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CreatePuzzleJFrame
     */
    private int lastGridSize = 4;
    
    public CreatePuzzleJFrame() {
        //create table model
        
        initComponents();
        HelpfulStaticFunctions.locateAtCentre(this);
        
        //make jSpinners non-editable
        ((DefaultEditor) boxSizejSpinner.getEditor()).getTextField().setEditable(false);
        ((DefaultEditor) gridSizejSpinner.getEditor()).getTextField().setEditable(false);
        puzzlejTable.setGridColor(Color.BLACK);
        //set table model
//        DefaultTableModel model = new javax.swing.table.DefaultTableModel(lastGridSize, lastGridSize);
//        puzzlejTable.setModel(model);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        TitlejLabel = new javax.swing.JLabel();
        ControlsjPanel = new javax.swing.JPanel();
        gridSizejSpinner = new javax.swing.JSpinner();
        gridSizejLabel = new javax.swing.JLabel();
        boxSizejLabel = new javax.swing.JLabel();
        boxSizejSpinner = new javax.swing.JSpinner();
        settingsjButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        puzzlejPanel = new javax.swing.JPanel();
        puzzlejScrollPane = new javax.swing.JScrollPane();
        puzzlejTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crossword Puzzle Creator");
        setMinimumSize(null);
        setResizable(false);

        TitlejLabel.setBackground(new java.awt.Color(204, 204, 204));
        TitlejLabel.setFont(new java.awt.Font("Luminari", 0, 36)); // NOI18N
        TitlejLabel.setForeground(new java.awt.Color(204, 0, 0));
        TitlejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitlejLabel.setText("Crossword Puzzle Creator");
        TitlejLabel.setToolTipText("");

        gridSizejSpinner.setModel(new javax.swing.SpinnerNumberModel(4, 4, 10, 1));
        gridSizejSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                gridSizejSpinnerStateChanged(evt);
            }
        });

        gridSizejLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        gridSizejLabel.setText("Grid Size (N x N) :");

        boxSizejLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        boxSizejLabel.setText("Box Size:");

        boxSizejSpinner.setModel(new javax.swing.SpinnerNumberModel(40, 10, 90, 2));
        boxSizejSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                boxSizejSpinnerStateChanged(evt);
            }
        });

        settingsjButton.setText("Settings");
        settingsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlsjPanelLayout = new javax.swing.GroupLayout(ControlsjPanel);
        ControlsjPanel.setLayout(ControlsjPanelLayout);
        ControlsjPanelLayout.setHorizontalGroup(
            ControlsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlsjPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gridSizejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gridSizejSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boxSizejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxSizejSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(settingsjButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ControlsjPanelLayout.setVerticalGroup(
            ControlsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlsjPanelLayout.createSequentialGroup()
                .addGroup(ControlsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ControlsjPanelLayout.createSequentialGroup()
                        .addGroup(ControlsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gridSizejSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gridSizejLabel)
                            .addComponent(boxSizejSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxSizejLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ControlsjPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(settingsjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)))
                .addContainerGap())
        );

        puzzlejScrollPane.setEnabled(false);

        puzzlejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {" ", " ", " ", " "},
                {" ", " ", " ", " "},
                {" ", " ", " ", " "},
                {" ", " ", " ", " "}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        puzzlejTable.setAutoscrolls(false);
        puzzlejTable.setShowGrid(true);
        puzzlejTable.setTableHeader(null);

        javax.swing.GroupLayout puzzlejPanelLayout = new javax.swing.GroupLayout(puzzlejPanel);
        puzzlejPanel.setLayout(puzzlejPanelLayout);
        puzzlejPanelLayout.setHorizontalGroup(
            puzzlejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puzzlejPanelLayout.createSequentialGroup()
                .addComponent(puzzlejScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        puzzlejPanelLayout.setVerticalGroup(
            puzzlejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puzzlejPanelLayout.createSequentialGroup()
                .addComponent(puzzlejScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(puzzlejPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puzzlejPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton3.setText("Generate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButton4)
                .addGap(29, 29, 29)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 230, Short.MAX_VALUE)
                .addComponent(TitlejLabel)
                .addGap(0, 230, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ControlsjPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitlejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ControlsjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void settingsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsjButtonActionPerformed
        this.setEnabled(false);
        new SettingsJFrame(this).setVisible(true);
    }//GEN-LAST:event_settingsjButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setEnabled(false);
        new SavePuzzleJFrame(this).setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void boxSizejSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_boxSizejSpinnerStateChanged
                //boxSize is new rows' width and columns' height 
        int boxSize = (int)boxSizejSpinner.getValue();

        //set new height for all rows
        puzzlejTable.setRowHeight(boxSize);

        //set new width for all columns
        TableColumnModel columnModel = puzzlejTable.getColumnModel();
        int columnCount = columnModel.getColumnCount();

        int newWidth = boxSize*columnCount+4;
        int newHeight = boxSize*puzzlejTable.getRowCount()+4;//+4 to avoid scroll bar
        puzzlejScrollPane.setSize(new Dimension(newWidth, newHeight));
        
//        for(int col=0; col< columnCount; col++){
//            columnModel.getColumn(col).setPreferredWidth(boxSize);
//        } 
    }//GEN-LAST:event_boxSizejSpinnerStateChanged

    private void gridSizejSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_gridSizejSpinnerStateChanged
        //gridSize is no of rows and columns 
        int gridSize = (int)gridSizejSpinner.getValue();
//        if(lastGridSize > gridSize){
//            //reduce one column
//        }
//        else{
//            //add one column
//        puzzlejTable.getColumnModel().addColumn(new TableColumn(lastGridSize));
//            
//        }
        
        puzzlejTable.setModel(new javax.swing.table.DefaultTableModel(gridSize, gridSize));
        boxSizejSpinnerStateChanged(evt);
//        //set new width for all columns
//        TableColumnModel columnModel = puzzlejTable.getColumnModel();
//        columnModel.addColumn(new TableColumn(WIDTH));
        
//        lastGridSize = gridSize;
    }//GEN-LAST:event_gridSizejSpinnerStateChanged

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlsjPanel;
    private javax.swing.JLabel TitlejLabel;
    private javax.swing.JLabel boxSizejLabel;
    private javax.swing.JSpinner boxSizejSpinner;
    private javax.swing.JLabel gridSizejLabel;
    private javax.swing.JSpinner gridSizejSpinner;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel puzzlejPanel;
    private javax.swing.JScrollPane puzzlejScrollPane;
    private javax.swing.JTable puzzlejTable;
    private javax.swing.JButton settingsjButton;
    // End of variables declaration//GEN-END:variables

    private void updatePuzzleTable() {
        }
}
